// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRrseVxQA8K3a1RCnZKqBKR1g4nWKrhYo',
    appId: '1:681758766010:web:627406be6bfa653b6e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    authDomain: 'bazar-suez-app.firebaseapp.com',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuSD2l5deFdKPfW944a40LlrZvu9Ukm6c',
    appId: '1:681758766010:android:a6ab367fb90d43206e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgM95OcGbR3lHbtRdOXo4nwazI_5zcuZk',
    appId: '1:681758766010:ios:94d8413e2cd2c16f6e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
    iosBundleId: 'com.example.bazarSuez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgM95OcGbR3lHbtRdOXo4nwazI_5zcuZk',
    appId: '1:681758766010:ios:94d8413e2cd2c16f6e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
    iosBundleId: 'com.example.bazarSuez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRrseVxQA8K3a1RCnZKqBKR1g4nWKrhYo',
    appId: '1:681758766010:web:b5e045173e273b0b6e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    authDomain: 'bazar-suez-app.firebaseapp.com',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
  );
}
